cloudflare/1.1.1.1

source/utilities/i18n/lang/fr.json

This completes the french translation!

Complete french translation

---

source/pages/ko-KR.pug
source/utilities/i18n/lang/index.ts
source/utilities/i18n/lang/ko-KR.json
webpack.config.ts

Enables Korean (한국어) menu under ko-KR/. Messages are fully translated.

Korean translation

---

source/utilities/i18n/lang/zh-CHT.json

\n\n\n\n\nzh-cht | source/utilities/i18n/lang/en-US.json | 161 strings\n \n cc @cloudflare

Localized strings (ja-jp, es-es, zh-cht, fr-fr, de-de, zh-chs) for the Update en-US.json pull request on imvenkat-qordoba-test

---

source/utilities/i18n/lang/de-DE.json
source/utilities/i18n/lang/en-US.json
source/utilities/i18n/lang/es-ES.json
source/utilities/i18n/lang/fr-FR.json
source/utilities/i18n/lang/ja-JP.json
source/utilities/i18n/lang/ko-KR.json
source/utilities/i18n/lang/nl-NL.json
source/utilities/i18n/lang/pt-BR.json
source/utilities/i18n/lang/zh-Hans.json
source/utilities/i18n/lang/zh-Hant.json

IPv6 address ``2606:4700:4700:1111`` and ``2606:4700:4700:1001`` added to all languages.

added ipv6 addresses to install instructions for all present languages

---

source/pages/tr-TR/help/index.pug
source/pages/tr-TR/index.pug
source/utilities/i18n/lang/index.ts
source/utilities/i18n/lang/tr-TR.json
webpack.config.ts

This PR adds Turkish translation.

Türkçe çeviri ekle

---

source/utilities/i18n/lang/nl-NL.json

Fix dutch grammar (per RES-260).

Fix dutch grammar

---

source/pages/help.ts
source/pages/partials/help.pug
source/styles/help.styl

Added copy to debug help page

---

source/pages/de-DE/purge-cache/index.pug
source/pages/en-US/purge-cache/index.pug
source/pages/es-ES/purge-cache/index.pug
source/pages/fr-FR/purge-cache/index.pug
source/pages/ja-JP/purge-cache/index.pug
source/pages/ko-KR/purge-cache/index.pug
source/pages/nl-NL/purge-cache/index.pug
source/pages/partials/purge-cache-base.pug
source/pages/partials/purge-cache.pug
source/pages/pt-BR/purge-cache/index.pug
source/pages/purge-cache.ts
source/pages/tr-TR/purge-cache/index.pug
source/pages/zh-Hans/purge-cache/index.pug
source/pages/zh-Hant/purge-cache/index.pug
source/styles/base.styl
source/styles/purge-cache.styl
webpack.config.ts

Let's deploy the current UI so we can test further. We can do any design tweaks and/or fixes after.
Current layout looks like:
Page will be available at: https://1.1.1.1/purge-cache/
It's hitting the endpoint at: `/v1/api/purge`

RES-294: Cache Purge UI

---

source/pages/purge-cache.ts

- Rename `/v1/api` to `/api/v1`
- URL encode query string params
- Parse message from response JSON

RES-294 - Adjust to API spec

---

source/pages/partials/help.pug
source/pages/partials/purge-cache.pug
source/styles/help.styl
source/styles/purge-cache.styl

Update visual styles - see screenshots

---

source/pages/partials/purge-cache.pug
source/styles/base.styl
source/styles/help.styl
source/styles/purge-cache.styl

This is a follow up PR to the previous one that address the comments Vasturiano left.
- Missing "." in two places
- Unnecessary code for Help.styl (H2 styles)
- Moving colors into Base.styl

Purge cache visual update

---

source/pages/partials/footer.pug

added the link to the footer section.

Update footer.pug with link to purge cache

---

source/pages/help.ts

RES-421: Prepend XHR calls to is-* with uuid

---

source/pages/partials/purge-cache.pug

RES-439: Remove SOA record type

---

source/pages/partials/purge-cache.pug

RES-440: Remove combo 'A, AAAA, CNAME, MX' record type option

---

source/pages/partials/base.pug

Updating gtm per Dragos' request.
He wants top of head and top of body for no script.

MRK-7859 Syncing gtm creds across properties

---

source/pages/partials/base.pug
source/pages/partials/explanation.pug
source/utilities/i18n/lang/de_de/de_de.json
source/utilities/i18n/lang/en-US.json
source/utilities/i18n/lang/es_es/en-US-en_us-es_es-CR-C.json
source/utilities/i18n/lang/es_es/es_es.json
source/utilities/i18n/lang/fr_fr/fr_fr.json
source/utilities/i18n/lang/id/id.json
source/utilities/i18n/lang/ja_jp/ja_jp.json
source/utilities/i18n/lang/ko/ko.json
source/utilities/i18n/lang/nl/nl.json
source/utilities/i18n/lang/pt_br/pt_br.json
source/utilities/i18n/lang/tr/tr.json
source/utilities/i18n/lang/zh_cn/zh_cn.json
source/utilities/i18n/lang/zh_tw/zh_tw.json

1. Update bar graph statistics and add timestamp
2. Update "13 million domains" to "16 million Internet properties"
3. Remove "28% faster"

Change and update copy

---

source/pages/partials/base.pug
source/utilities/i18n/lang/en-US.json

Moved English strings to the `en-US.json` file.

String extract homepage for translation

---

Makefile

This reverts commit cf686030b45b221aacb45fadfca099711ae609d8.

Revert "Removed deprecated bucket"

---

source/styles/components/easter-egg-section.css

This adjusts the easter egg in the footer so it doesn't continuously scroll the page but instead makes it look intentional

MRK-14464 - Adjust footer top padding and add z index to show meteor

---

source/utilities/i18n/lang/en-US.json

MRK-15488: Update WARP+ description
